Kuan New api
andy89923/nf-example pull request #14
Opened 2024-11-13 10:38 UTC by senselessDog

2024-11-14 03:50 UTC, senselessDog commented
second time try for golangci-lint

2024-11-14 04:30 UTC, andy89923 commented
There are 6 actions which is not correct.

2024-12-07 06:09 UTC, andy89923 requested changes
@senselessDog 
Please resolve the conflicts!

2024-12-07 06:10 UTC, andy89923 commented
Also, do not use Chinese in the comments.

2024-12-18 10:42 UTC, senselessDog commented
Okay. I resolve the conflict

2024-12-18 16:04 UTC, senselessDog commented
These two file have a deplicate issue. I try to use //nolint:dupl to fix it

2024-12-29 18:55 UTC, andy89923 commented
Try to squash commit using rebase.

2026-02-06 16:30 UTC, closed without merging