feat: add hello API with GET and POST endpoints and tests
andy89923/nf-example pull request #16
Opened 2024-12-10 15:20 UTC by williamlin0518

feat: add hello API with GET and POST endpoints and tests

2024-12-12 09:12 UTC, andy89923 commented
@williamlin0518 Please fix the linter errors.

2025-01-01 16:11 UTC, andy89923 requested changes

2025-01-01 16:11 UTC, andy89923 commented on internal/sbi/api_chiikawa_test.go
> +//nolint:dupl
Rebase branch and remove this line

2025-01-01 16:11 UTC, andy89923 commented on internal/sbi/api_hello_test.go
> +//nolint:dupl
Rebase branch and remove this line

2025-01-01 16:11 UTC, andy89923 commented on internal/sbi/api_hi_test.go
> +//nolint:dupl
Rebase branch and remove this line

2025-01-01 16:12 UTC, andy89923 commented
And try to squash the commits for linter fixes.

2025-01-02 00:10 UTC, williamlin0518 commented on internal/sbi/api_hi_test.go
> +//nolint:dupl
```
vboxuser@OS2:~/proj/nf-example$ git pull origin stu/113
From https://github.com/williamlin0518/nf-example
 * branch            stu/113    -> FETCH_HEAD
Already up to date.
vboxuser@OS2:~/proj/nf-example$ git checkout feature/hello
Switched to branch 'feature/hello'
vboxuser@OS2:~/proj/nf-example$ git rebase stu/113
Current branch feature/hello is up to date.
```

![image](https://github.com/user-attachments/assets/ccac5c52-7ccf-447b-95d0-de7dfcce3915)
similar pattern to api_chiikawa_test.go and api_hi_test.go
@andy89923  please more in detail, thanks

2025-01-02 01:04 UTC, andy89923 commented on internal/sbi/api_hi_test.go
> +//nolint:dupl
https://github.com/andy89923/nf-example/commit/66f0129cbfd862ebb245d4df32173a9a4e454a13

2025-01-02 01:52 UTC, williamlin0518 commented
> And try to squash the commits for linter fixes.

squash below commit 

```
a2e0efb style: fix linting issues
cbc0c67 fix: fix the test
755c021 fix: fix the linter
```

2025-01-02 02:03 UTC, andy89923 approved these changes

2025-01-02 02:04 UTC, merged